### ISSUE TITLE
Cmake fails to checkout dependency

### ISSUE THREAD

**Issue by RickLuiken** [suzizecat/slang-lsp-tools#13]
Hi @suzizecat!

While trying to build the project, I came across the following error:

```bash
[ 11%] Performing download step (git clone) for 'uri-populate'
[ 11%] Creating directories for 'uri-populate'
[ 22%] Performing download step (git clone) for 'uri-populate'
Cloning into 'uri-src'...
fatal: invalid reference: 23690f8
CMake Error at uri-subbuild/uri-populate-prefix/tmp/uri-populate-gitclone.cmake:49 (message):
  Failed to checkout tag: '23690f8'


gmake[2]: *** [CMakeFiles/uri-populate.dir/build.make:102: uri-populate-prefix/src/uri-populate-stamp/uri-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/uri-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

I am not an expert at Cmake, but with a bit of googling it might have to do something with this issue: https://gitlab.kitware.com/cmake/cmake/-/issues/23379

Temporarily changing the checkout tag to master seems to fix the issue

**Comment by suzizecat** [comment]
Hi @RickLuiken !

You are indeed right (and I am wondering how the CD process seemed to have worked...)
I would rather not use `master` as a qualifier (as this would change the reference if the author of URI pushes a commit...) but the solution is to set `GIT_SHALLOW OFF`.

I will update master once I get a bit more time to actively work on this.
